export const SET_FILTERS = "SET_FILTERS";
export const SET_SELECTED_FILTERS = "SET_SELECTED_FILTERS";
export const SET_DATA = "SET_DATA";
export const SET_SHORTLISTED = "SET_SHORTLISTED";
export const SET_DATA_LOADED = "SET_DATA_LOADED";
export const SET_BUDGET = "SET_BUDGET";
